### ISSUE TITLE
Ideas for CG refresh Sep 2021

### ISSUE THREAD

**Issue by ericvd-ucb** [ds-modules/curriculum-guide#14]
@balajialg some ideas for CG refresh

- [x] redo first page - this is for people using the campus jupyterhub to teach
- [x] redo the order of sections

- [x] Move Pedagogy and Technology to Section 1 - Getting started about the campus Jupyterhub
- [x] Move FAQ up to be in this section 
- [x] Move large datasets and Pyhton packages to this setion
- [x] redo references to DSEP to say CDSS

- [x] Section 2  - workflow basics 
- [x] Delete every mention on OK py and start to refer people to Otter documentation
- [x] Discuss options for downloading pdfs - screenshot of downlad pdf via hmtl

- [x] Move Connector / Module ? DEC to a Section 3
- [x] Section 4 - Creating a connector 
- [x] Section 5 creating a Module

- [x] Redo Logistics Room and Technology page
- [x] Delete Classrooms section
- [ ] Redo resources for students - laptop lending - double chekc this data
- [x] redo who are we - people page?
- [x] redo contact page

**Comment by balajialg** [comment]
@ericvd-ucb Sounds great! I will work on it. thanks
