### ISSUE TITLE
add in Github desktop flow

### ISSUE THREAD

**Issue by ericvd-ucb** [ds-modules/curriculum-guide#29]
I think it woudl make sense to add in a page on how to do all this with Github Desktop app

**Comment by balajialg** [comment]
@ericvd-ucb Created draft documentation for Github Desktop [here ](https://ds-modules.github.io/curriculum-guide/technology/git-and-github.html?highlight=github%20desktop#github-desktop)! Anything else you would want to highlight in this documentation?
